services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres-17-target
    ports:
      - 5678:5432
    volumes:
      - ~/apps/postgres-17-target:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=targetPassword
      - POSTGRES_USER=targetUsername
      - POSTGRES_DB=INB
  postgres_src1:
    image: postgres:17-bookworm
    container_name: postgres-17-src1
    ports:
      - 5001:5432
    volumes:
      - ~/apps/postgres-17-src1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=src1Password
      - POSTGRES_USER=src1Username
      - POSTGRES_DB=src
  postgres_src2:
    image: postgres:17-bookworm
    container_name: postgres-17-src2
    ports:
      - 5002:5432
    volumes:
      - ~/apps/postgres-17-src2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=src2Password
      - POSTGRES_USER=src2Username
      - POSTGRES_DB=src